/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        ProductController classUnderTest = new ProductController();
        assertNotNull("supermarchéenligne fonctionne correctement", classUnderTest.getNom());
    }
}
